Vagrant.configure("2") do |config|
    # config.vbguest.auto_update = false
    # test linux 
    # 연습으로 깡통 리눅스만 올려 봅니다. 
    # vagrant up test 명령이 실행 완료되면, 리눅스 가상머신이 생성됩니다.
    # vagrant ssh test 로 리눅스 운영체제에 콘솔 연결할 수 있습니다. 
    config.vm.define "test" do |vname|
        vname.vm.box = "ubuntu"
        vname.vm.hostname = "test"

        vname.trigger.before :halt do |trigger|
            trigger.warn = "graceful shutdown hook"
            trigger.run_remote = {inline: "echo 'test machine is now shutting down'"}
        end

        vname.vm.provider "virtualbox" do |vb|
            vb.name = "test"
            vb.customize ['modifyvm', :id, '--audio', 'none']
            vb.memory = 2000
            vb.cpus = 2
        end
        vname.vm.network "private_network", ip: "192.168.56.10"
    end

    # # Docker VM
    # config.vm.define "dock" do |machine|
    #     #config.vbguest.auto_update = false 
    #     machine.vm.box = "ubuntu"
    #     machine.vm.hostname = "dock"
    #     machine.vm.provider "virtualbox" do |vb|
    #         vb.name = "dock"
    #         vb.customize ["modifyvm", :id, "--audio", "none"]
    #         vb.memory = 3000
    #         vb.cpus = 2
    #     end
    #     machine.vm.network "private_network", ip: "192.168.56.10"
    #     machine.vm.provision "shell", path: "./shells/boot_docker.sh", run: "once"
    # end
end