Vagrant.configure("2") do |config|
    # config.vbguest.auto_update = false
    # 192.168.56.xx 에서 .2x 대역을 spark machine으로 사용할 예정  
    # spark-client 는 .29 번 사용
    # spark-client  
    # spark 개발에 사용할 적당한 메모리와 cpu core를 할당한다.
    # 코드 작성 중인 노트북은 사양이 낮아서 memory 4G, cpu 2 core만 할당했음.  
    config.vm.define "spark-client" do |vname|
        vname.vm.box = "ubuntu"
        vname.vm.hostname = "spark-client"

        vname.trigger.before :halt do |trigger|
            trigger.warn = "graceful shutdown hook"
            trigger.run_remote = {inline: "echo 'test machine is now shutting down'"}
        end

        vname.vm.provider "virtualbox" do |vb|
            vb.name = "spark-client"
            vb.customize ['modifyvm', :id, '--audio', 'none']
            vb.memory = 4000
            vb.cpus = 2
        end
        vname.vm.network "private_network", ip: "192.168.56.29"
    end

    # # Docker VM
    # config.vm.define "dock" do |machine|
    #     #config.vbguest.auto_update = false 
    #     machine.vm.box = "ubuntu"
    #     machine.vm.hostname = "dock"
    #     machine.vm.provider "virtualbox" do |vb|
    #         vb.name = "dock"
    #         vb.customize ["modifyvm", :id, "--audio", "none"]
    #         vb.memory = 3000
    #         vb.cpus = 2
    #     end
    #     machine.vm.network "private_network", ip: "192.168.56.10"
    #     machine.vm.provision "shell", path: "./shells/boot_docker.sh", run: "once"
    # end
end